# Loki Configuration for SightEdit Log Aggregation

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  
  filesystem:
    directory: /loki/chunks

limits_config:
  # Ingestion limits
  ingestion_rate_mb: 64
  ingestion_burst_size_mb: 128
  max_streams_per_user: 10000
  max_line_size: 256KB
  
  # Query limits
  max_query_parallelism: 32
  max_query_series: 1000000
  max_query_lookback: 0s
  
  # Retention
  retention_period: 30d
  
  # Stream limits
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  max_concurrent_tail_requests: 100
  
  # Chunk encoding
  chunk_encoding: snappy
  
  # Reject old samples
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 1 week
  
  # Split queries
  split_queries_by_interval: 15m

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 30d

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_sharding: false

analytics:
  reporting_enabled: false

# Compactor for cleaning up old data
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# Query frontend for better query performance
frontend:
  max_outstanding_per_tenant: 2048
  compress_responses: true
  downstream_url: http://localhost:3100

frontend_worker:
  frontend_address: localhost:9095
  grpc_client_config:
    max_send_msg_size: 104857600 # 100MB

# Querier configuration
querier:
  query_ingesters_within: 3h
  query_timeout: 1m
  tail_max_duration: 1h
  extra_query_delay: 0s

# Ingester configuration
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
    
  # WAL (Write Ahead Log)
  wal:
    enabled: true
    dir: /loki/wal
    replay_memory_ceiling: 1GB
    
  # Chunk settings
  chunk_idle_period: 30m
  chunk_retain_period: 1m
  max_chunk_age: 1h
  chunk_target_size: 1536000 # 1.5MB
  chunk_encoding: snappy
  
  # Flush settings
  flush_check_period: 30s
  flush_op_timeout: 10s

# Index gateway for better index queries
index_gateway:
  mode: simple