# Alertmanager Configuration for SightEdit Production

global:
  # SMTP configuration
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@sightedit.com'
  smtp_auth_username: 'alerts@sightedit.com'
  smtp_auth_password: 'your_smtp_password'
  smtp_require_tls: true

  # Slack webhook for critical alerts
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

  # External alert API
  http_config:
    proxy_url: 'http://proxy.company.com:8080'

# Templates for alert notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing rules
route:
  # Root route - all alerts start here
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s        # Wait time before sending the first notification
  group_interval: 5m     # Wait time before sending notifications about new alerts in a group
  repeat_interval: 4h    # Wait time before resending a notification
  receiver: 'default'

  # Specific routing rules
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      group_interval: 2m
      repeat_interval: 30m
      
    # Security alerts - immediate notification
    - match:
        category: security
      receiver: 'security-team'
      group_wait: 0s
      group_interval: 1m
      repeat_interval: 15m
      continue: true  # Continue processing other routes
      
    # Business alerts - during business hours
    - match:
        category: business
      receiver: 'business-team'
      active_time_intervals:
        - business_hours
      
    # Infrastructure alerts
    - match:
        category: infrastructure
      receiver: 'infrastructure-team'
      
    # Application alerts
    - match_re:
        service: '^sightedit-.*'
      receiver: 'app-team'
      
    # Database alerts
    - match_re:
        service: '^(postgres|redis|mongodb)-.*'
      receiver: 'database-team'
      
    # Warning level alerts - less frequent
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_interval: 10m
      repeat_interval: 2h

# Time intervals for business hours routing
time_intervals:
  - name: business_hours
    time_intervals:
      - times:
          - start_time: '09:00'
            end_time: '17:00'
        weekdays: ['monday:friday']
        location: 'America/New_York'

# Inhibition rules - suppress certain alerts when others are firing
inhibit_rules:
  # Suppress instance down alerts when entire cluster is down
  - source_match:
      alertname: 'ClusterDown'
    target_match:
      alertname: 'InstanceDown'
    equal: ['cluster']

  # Suppress high CPU alerts when instance is down
  - source_match:
      alertname: 'InstanceDown'
    target_match_re:
      alertname: '^(HighCPU|HighMemory|HighDisk).*'
    equal: ['instance']

  # Suppress warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['service', 'instance']

# Notification receivers
receivers:
  # Default catch-all receiver
  - name: 'default'
    webhook_configs:
      - url: 'http://webhook-server:8080/alerts/default'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'webhook_user'
            password: 'webhook_password'

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@sightedit.com'
        subject: '[CRITICAL] {{ .GroupLabels.alertname }} - {{ .GroupLabels.service }}'
        body: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Severity:** {{ .Labels.severity }}
          **Service:** {{ .Labels.service }}
          **Instance:** {{ .Labels.instance }}
          **Description:** {{ .Annotations.description }}
          **Runbook:** {{ .Annotations.runbook_url }}
          **Dashboard:** {{ .Annotations.dashboard }}
          **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
        html: |
          <h3>Critical Alert: {{ .GroupLabels.alertname }}</h3>
          <table border="1" style="border-collapse: collapse;">
          <tr><th>Field</th><th>Value</th></tr>
          {{ range .Alerts }}
          <tr><td>Alert</td><td>{{ .Annotations.summary }}</td></tr>
          <tr><td>Severity</td><td><span style="color: red;">{{ .Labels.severity }}</span></td></tr>
          <tr><td>Service</td><td>{{ .Labels.service }}</td></tr>
          <tr><td>Instance</td><td>{{ .Labels.instance }}</td></tr>
          <tr><td>Description</td><td>{{ .Annotations.description }}</td></tr>
          <tr><td>Runbook</td><td><a href="{{ .Annotations.runbook_url }}">{{ .Annotations.runbook_url }}</a></td></tr>
          <tr><td>Dashboard</td><td><a href="{{ .Annotations.dashboard }}">{{ .Annotations.dashboard }}</a></td></tr>
          <tr><td>Started</td><td>{{ .StartsAt.Format "2006-01-02 15:04:05" }}</td></tr>
          {{ end }}
          </table>
          
    slack_configs:
      - api_url: '{{ .GlobalParams.slack_api_url }}'
        channel: '#alerts-critical'
        title: ':rotating_light: CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          *Description:* {{ .Annotations.description }}
          *Runbook:* <{{ .Annotations.runbook_url }}|View Runbook>
          *Dashboard:* <{{ .Annotations.dashboard }}|View Dashboard>
          {{ end }}
        color: 'danger'
        send_resolved: true

    pagerduty_configs:
      - routing_key: 'your_pagerduty_integration_key'
        description: '{{ .GroupLabels.alertname }}: {{ .GroupLabels.service }}'
        details:
          severity: '{{ .GroupLabels.severity }}'
          service: '{{ .GroupLabels.service }}'
          instance: '{{ .GroupLabels.instance }}'
        links:
          - href: '{{ .Annotations.runbook_url }}'
            text: 'Runbook'
          - href: '{{ .Annotations.dashboard }}'
            text: 'Dashboard'

  # Security team alerts
  - name: 'security-team'
    email_configs:
      - to: 'security@sightedit.com'
        subject: '[SECURITY] {{ .GroupLabels.alertname }}'
        body: |
          Security Alert Detected
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Type: {{ .Labels.category }}
          Source IP: {{ .Labels.source_ip }}
          User: {{ .Labels.user_id }}
          Description: {{ .Annotations.description }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05 MST" }}
          {{ end }}
          
          Immediate action may be required.

    slack_configs:
      - api_url: '{{ .GlobalParams.slack_api_url }}'
        channel: '#security-alerts'
        title: ':warning: Security Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Type:* {{ .Labels.category }}
          *Description:* {{ .Annotations.description }}
          *Source IP:* {{ .Labels.source_ip }}
          *User:* {{ .Labels.user_id }}
          {{ end }}
        color: '#ff6600'

  # Business team alerts
  - name: 'business-team'
    email_configs:
      - to: 'business@sightedit.com'
        subject: '[BUSINESS] {{ .GroupLabels.alertname }}'
        body: |
          Business Metric Alert
          
          {{ range .Alerts }}
          Metric: {{ .Annotations.summary }}
          Current Value: {{ .Labels.value }}
          Threshold: {{ .Annotations.threshold }}
          Impact: {{ .Annotations.business_impact }}
          {{ end }}

  # Infrastructure team alerts
  - name: 'infrastructure-team'
    email_configs:
      - to: 'infrastructure@sightedit.com'
        subject: '[INFRA] {{ .GroupLabels.alertname }} - {{ .GroupLabels.instance }}'
        body: |
          Infrastructure Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Instance: {{ .Labels.instance }}
          Description: {{ .Annotations.description }}
          {{ end }}

    slack_configs:
      - api_url: '{{ .GlobalParams.slack_api_url }}'
        channel: '#infrastructure'
        title: 'Infrastructure Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Instance:* {{ .Labels.instance }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

  # Application team alerts
  - name: 'app-team'
    email_configs:
      - to: 'dev-team@sightedit.com'
        subject: '[APP] {{ .GroupLabels.alertname }} - {{ .GroupLabels.service }}'
        body: |
          Application Alert
          
          {{ range .Alerts }}
          Service: {{ .Labels.service }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}

    slack_configs:
      - api_url: '{{ .GlobalParams.slack_api_url }}'
        channel: '#development'
        title: 'App Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Service:* {{ .Labels.service }}
          *Description:* {{ .Annotations.description }}
          *Runbook:* <{{ .Annotations.runbook_url }}|View>
          {{ end }}

  # Database team alerts
  - name: 'database-team'
    email_configs:
      - to: 'dba@sightedit.com'
        subject: '[DB] {{ .GroupLabels.alertname }} - {{ .GroupLabels.service }}'
        body: |
          Database Alert
          
          {{ range .Alerts }}
          Database: {{ .Labels.service }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

  # Warning level alerts
  - name: 'warning-alerts'
    email_configs:
      - to: 'monitoring@sightedit.com'
        subject: '[WARNING] {{ .GroupLabels.alertname }}'
        body: |
          Warning Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Service: {{ .Labels.service }}
          Description: {{ .Annotations.description }}
          {{ end }}

    slack_configs:
      - api_url: '{{ .GlobalParams.slack_api_url }}'
        channel: '#alerts-warning'
        title: 'Warning: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Service:* {{ .Labels.service }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        color: 'warning'