# SightEdit Application Alert Rules

groups:
  - name: sightedit.application.rules
    interval: 30s
    rules:
      # Application Availability
      - alert: SightEditBackendDown
        expr: up{job="sightedit-backend"} == 0
        for: 1m
        labels:
          severity: critical
          service: sightedit-backend
          category: availability
        annotations:
          summary: "SightEdit backend service is down"
          description: "SightEdit backend service {{ $labels.instance }} has been down for more than 1 minute"
          runbook_url: "https://docs.sightedit.com/runbooks/backend-down"
          dashboard: "https://monitoring.sightedit.com/d/sightedit-overview"
      
      # High Error Rate
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_requests_total{job="sightedit-backend",status=~"5.."}[5m])) by (instance)
            / 
            sum(rate(http_requests_total{job="sightedit-backend"}[5m])) by (instance)
          ) * 100 > 5
        for: 2m
        labels:
          severity: warning
          service: sightedit-backend
          category: performance
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for instance {{ $labels.instance }}"
          runbook_url: "https://docs.sightedit.com/runbooks/high-error-rate"
      
      - alert: CriticalErrorRate
        expr: |
          (
            sum(rate(http_requests_total{job="sightedit-backend",status=~"5.."}[5m])) by (instance)
            / 
            sum(rate(http_requests_total{job="sightedit-backend"}[5m])) by (instance)
          ) * 100 > 15
        for: 1m
        labels:
          severity: critical
          service: sightedit-backend
          category: performance
        annotations:
          summary: "Critical error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for instance {{ $labels.instance }}"
          runbook_url: "https://docs.sightedit.com/runbooks/critical-error-rate"
      
      # Response Time Alerts
      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.95, 
            sum(rate(http_request_duration_seconds_bucket{job="sightedit-backend"}[5m])) by (le, instance)
          ) > 1
        for: 2m
        labels:
          severity: warning
          service: sightedit-backend
          category: performance
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value | humanizeDuration }} for instance {{ $labels.instance }}"
          runbook_url: "https://docs.sightedit.com/runbooks/high-response-time"
      
      - alert: CriticalResponseTime
        expr: |
          histogram_quantile(0.95, 
            sum(rate(http_request_duration_seconds_bucket{job="sightedit-backend"}[5m])) by (le, instance)
          ) > 5
        for: 1m
        labels:
          severity: critical
          service: sightedit-backend
          category: performance
        annotations:
          summary: "Critical response time detected"
          description: "95th percentile response time is {{ $value | humanizeDuration }} for instance {{ $labels.instance }}"
          runbook_url: "https://docs.sightedit.com/runbooks/critical-response-time"
      
      # Traffic Volume
      - alert: LowTrafficVolume
        expr: sum(rate(http_requests_total{job="sightedit-backend"}[5m])) < 0.1
        for: 5m
        labels:
          severity: warning
          service: sightedit-backend
          category: business
        annotations:
          summary: "Unusually low traffic volume"
          description: "Request rate is {{ $value | humanize }} requests/second, which is unusually low"
          runbook_url: "https://docs.sightedit.com/runbooks/low-traffic"
      
      - alert: HighTrafficVolume
        expr: sum(rate(http_requests_total{job="sightedit-backend"}[5m])) > 100
        for: 1m
        labels:
          severity: warning
          service: sightedit-backend
          category: capacity
        annotations:
          summary: "High traffic volume detected"
          description: "Request rate is {{ $value | humanize }} requests/second, consider scaling"
          runbook_url: "https://docs.sightedit.com/runbooks/high-traffic"

  - name: sightedit.business.rules
    interval: 60s
    rules:
      # Editor Usage Metrics
      - alert: LowEditorUsage
        expr: |
          sum(increase(sightedit_editor_activations_total[1h])) < 10
        for: 5m
        labels:
          severity: warning
          category: business
        annotations:
          summary: "Low editor usage detected"
          description: "Only {{ $value }} editor activations in the last hour"
          runbook_url: "https://docs.sightedit.com/runbooks/low-editor-usage"
      
      # Save Operations
      - alert: HighSaveFailureRate
        expr: |
          (
            sum(increase(sightedit_save_operations_total{status="failed"}[5m]))
            /
            sum(increase(sightedit_save_operations_total[5m]))
          ) * 100 > 10
        for: 2m
        labels:
          severity: warning
          category: business
        annotations:
          summary: "High save failure rate"
          description: "{{ $value | humanizePercentage }} of save operations are failing"
          runbook_url: "https://docs.sightedit.com/runbooks/save-failures"
      
      # User Sessions
      - alert: AbnormalSessionDuration
        expr: |
          histogram_quantile(0.50, 
            sum(rate(sightedit_session_duration_seconds_bucket[10m])) by (le)
          ) < 60
        for: 5m
        labels:
          severity: info
          category: business
        annotations:
          summary: "Abnormally short user sessions"
          description: "Median session duration is {{ $value | humanizeDuration }}"
      
      # API Key Usage
      - alert: SuspiciousAPIKeyUsage
        expr: |
          sum by (api_key_id) (rate(sightedit_api_requests_total[5m])) > 50
        for: 1m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "Suspicious API key usage pattern"
          description: "API key {{ $labels.api_key_id }} is making {{ $value }} requests/second"
          runbook_url: "https://docs.sightedit.com/runbooks/suspicious-api-usage"

  - name: sightedit.infrastructure.rules
    interval: 30s
    rules:
      # CPU Usage
      - alert: HighCPUUsage
        expr: |
          100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
          runbook_url: "https://docs.sightedit.com/runbooks/high-cpu"
      
      - alert: CriticalCPUUsage
        expr: |
          100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 95
        for: 1m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "Critical CPU usage detected"
          description: "CPU usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
          runbook_url: "https://docs.sightedit.com/runbooks/critical-cpu"
      
      # Memory Usage
      - alert: HighMemoryUsage
        expr: |
          (
            (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) 
            / node_memory_MemTotal_bytes
          ) * 100 > 85
        for: 2m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
          runbook_url: "https://docs.sightedit.com/runbooks/high-memory"
      
      - alert: CriticalMemoryUsage
        expr: |
          (
            (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) 
            / node_memory_MemTotal_bytes
          ) * 100 > 95
        for: 1m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "Critical memory usage detected"
          description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
          runbook_url: "https://docs.sightedit.com/runbooks/critical-memory"
      
      # Disk Usage
      - alert: HighDiskUsage
        expr: |
          (
            (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) 
            / node_filesystem_size_bytes{fstype!="tmpfs"}
          ) * 100 > 85
        for: 5m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.instance }} ({{ $labels.mountpoint }})"
          runbook_url: "https://docs.sightedit.com/runbooks/high-disk"
      
      - alert: CriticalDiskUsage
        expr: |
          (
            (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) 
            / node_filesystem_size_bytes{fstype!="tmpfs"}
          ) * 100 > 95
        for: 1m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "Critical disk usage detected"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.instance }} ({{ $labels.mountpoint }})"
          runbook_url: "https://docs.sightedit.com/runbooks/critical-disk"
      
      # Network Issues
      - alert: HighNetworkErrors
        expr: |
          (
            rate(node_network_receive_errs_total[5m]) + 
            rate(node_network_transmit_errs_total[5m])
          ) > 10
        for: 2m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "High network error rate"
          description: "Network errors are {{ $value }} errors/second on {{ $labels.instance }}"
          runbook_url: "https://docs.sightedit.com/runbooks/network-errors"

  - name: sightedit.security.rules
    interval: 60s
    rules:
      # Failed Authentication Attempts
      - alert: HighFailedLoginAttempts
        expr: |
          sum(increase(sightedit_auth_attempts_total{status="failed"}[5m])) > 20
        for: 1m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "High number of failed login attempts"
          description: "{{ $value }} failed login attempts in the last 5 minutes"
          runbook_url: "https://docs.sightedit.com/runbooks/failed-logins"
      
      # Suspicious Request Patterns
      - alert: SuspiciousRequestPattern
        expr: |
          sum by (source_ip) (rate(http_requests_total{status=~"4.."}[1m])) > 10
        for: 2m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "Suspicious request pattern detected"
          description: "IP {{ $labels.source_ip }} is making {{ $value }} failed requests/second"
          runbook_url: "https://docs.sightedit.com/runbooks/suspicious-requests"
      
      # SQL Injection Attempts
      - alert: SQLInjectionAttempt
        expr: |
          increase(sightedit_security_violations_total{type="sql_injection"}[5m]) > 0
        for: 0m
        labels:
          severity: critical
          category: security
        annotations:
          summary: "SQL injection attempt detected"
          description: "{{ $value }} SQL injection attempts detected in the last 5 minutes"
          runbook_url: "https://docs.sightedit.com/runbooks/sql-injection"
      
      # XSS Attempts
      - alert: XSSAttempt
        expr: |
          increase(sightedit_security_violations_total{type="xss"}[5m]) > 0
        for: 0m
        labels:
          severity: critical
          category: security
        annotations:
          summary: "XSS attempt detected"
          description: "{{ $value }} XSS attempts detected in the last 5 minutes"
          runbook_url: "https://docs.sightedit.com/runbooks/xss-attempt"

  - name: sightedit.dependencies.rules
    interval: 30s
    rules:
      # Redis Connection
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
          service: redis
          category: dependency
        annotations:
          summary: "Redis is down"
          description: "Redis service is not responding"
          runbook_url: "https://docs.sightedit.com/runbooks/redis-down"
      
      # Database Connection
      - alert: DatabaseConnectionHigh
        expr: |
          sum(pg_stat_activity_count) by (instance) > 80
        for: 2m
        labels:
          severity: warning
          service: postgresql
          category: dependency
        annotations:
          summary: "High database connection count"
          description: "Database has {{ $value }} active connections"
          runbook_url: "https://docs.sightedit.com/runbooks/high-db-connections"
      
      # External API Issues
      - alert: ExternalAPIDown
        expr: up{job="blackbox-exporter"} == 0
        for: 2m
        labels:
          severity: warning
          category: dependency
        annotations:
          summary: "External API endpoint is down"
          description: "External endpoint {{ $labels.instance }} is not responding"
          runbook_url: "https://docs.sightedit.com/runbooks/external-api-down"